[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[profile.release]
panic='abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.3.1"
rand = "0.8.5"
